### ISSUE TITLE
Have you heard of pandoc?

### ISSUE THREAD

**Issue by Naereen** [parrt/bookish#2]
Hi!
This project seems mature and render quite nicely.
But it has some drawbacks in comparison to, let say, pandoc: no text access for the math, no accessibility features on equations, etc.
Maybe you would be interested by [pandoc](http://pandoc.org/MANUAL.html) ?
Just letting you know.
Regards.

**Comment by parrt** [comment]
yep, it is cool but I discarded it because it can't exec and display python etc...  And, as the antlr guy, building translators is easy for me :)

**Comment by Naereen** [comment]
I see. Thanks for your response!
